apiVersion: v1
kind: Service
metadata:
  name: ms-eventos
spec:
  selector:
    app: ms-eventos
  ports:
  - protocol: TCP
    port: 9084 # Puerto interno del servicio
    targetPort: 9084 # Puerto del contenedor
    nodePort: 30084 # Puerto expuesto en el nodo
  type: NodePort