apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-eventos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-eventos
  template:
    metadata:
      labels:
        app: ms-eventos
    spec:
      containers:
      - name: ms-eventos
        image: jyugar/ms-eventos:1.2
        args:
            - "--spring.config.additional-location=file:/config/"
        ports:
        - containerPort: 9084
        
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9084
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 3

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9084
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
        
        resources:
          requests:
            cpu: "400m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "800Mi"
      
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-eventos
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-eventos
                key: DB_PASSWORD
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: ms-eventos-config
                key: APP_NAME
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: ms-eventos-config
                key: SERVER_PORT
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: ms-eventos-config
                key: DB_URL
          - name: DB_DRIVER
            valueFrom:
              configMapKeyRef:
                name: ms-eventos-config
                key: DB_DRIVER
          - name: JPA_DDL_AUTO
            valueFrom:
              configMapKeyRef:
                name: ms-eventos-config
                key: JPA_DDL_AUTO
          - name: JPA_SHOW_SQL
            valueFrom:
              configMapKeyRef:
                name: ms-eventos-config
                key: JPA_SHOW_SQL
          - name: HIBERNATE_DIALECT
            valueFrom:
              configMapKeyRef:
                name: ms-eventos-config
                key: HIBERNATE_DIALECT
      
        volumeMounts:
          - name: config-volume
            mountPath: /config/application.yml
            subPath: application.yml
  
    volumes:
        - name: config-volume
          configMap:
            name: ms-participantes-config
            items:
              - key: application.yml
                path: application.yml